# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: /#about
    weight: 10
  - name: Experience
    url: 'experience'
    weight: 15
  - name: Projects
    url: /#projects
    weight: 20
  - name: Featured Work
    url: 'featured-publications'
    weight: 30
  - name: Publications
    url: 'publication'
    weight: 35
  - name: Collaborators
    url: 'collaborators'
    weight: 36
  - name: Talks
    url: 'event'
    weight: 37
  - name: Posts
    url: 'post'
    weight: 40
  - name: Media
    url: 'media'
    weight: 41
  - name: Contact
    url: /#contact
    weight: 60
# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/uploads/resume.pdf` and uncomment the lines below.
  - name: CV
    url: 'files/cv_CHAOFENGQING.pdf'
    weight: 70
