# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: About
    url: /about
    weight: 10
    identifier: 'about_parent'
  - name: Bio
    url: /#about
    parent: 'about_parent'
    weight: 1
  - name: Experience
    url: 'experience'
    parent: 'about_parent'
    weight: 2
  - name: Accomplishments
    url: 'accomplishments'
    parent: 'about_parent'
    weight: 3
  - name: CV
    url: 'files/cv_CHAOFENGQING.pdf'
    parent: 'about_parent'
    weight: 4
  - name: Lab
    url: /people
    weight: 11
  - name: Research
    url: 'publication'
    weight: 30
    identifier: 'pub_parent'
  - name: Projects
    url: 'projects'
    parent: 'pub_parent'
    weight: 1
  - name: Featured Articles
    url: 'featured-publications'
    parent: 'pub_parent'
    weight: 2
  - name: Full Publications
    url: 'publication'
    parent: 'pub_parent'
    weight: 3
  - name: Collaborators
    url: 'collaborators'
    weight: 36
  - name: Outreach
    url: 'publication'
    weight: 37
    identifier: 'out_parent'
  - name: Talks
    url: 'event'
    parent: 'out_parent'
    weight: 1
  - name: Media
    url: 'media'
    parent: 'out_parent'
    weight: 2
  - name: Posts
    url: 'post'
    weight: 40
  - name: Contact
    url: 'contact'
    weight: 60
